// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package psql_model

var TableNames = struct {
	Account        string
	Channel        string
	GorpMigrations string
	Message        string
}{
	Account:        "account",
	Channel:        "channel",
	GorpMigrations: "gorp_migrations",
	Message:        "message",
}
