// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package psql_model

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testInputs(t *testing.T) {
	t.Parallel()

	query := Inputs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testInputsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Inputs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInputsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Inputs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Inputs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInputsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := InputSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Inputs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInputsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := InputExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Input exists: %s", err)
	}
	if !e {
		t.Errorf("Expected InputExists to return true, but got false.")
	}
}

func testInputsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	inputFound, err := FindInput(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if inputFound == nil {
		t.Error("want a record, got nil")
	}
}

func testInputsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Inputs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testInputsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Inputs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testInputsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	inputOne := &Input{}
	inputTwo := &Input{}
	if err = randomize.Struct(seed, inputOne, inputDBTypes, false, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}
	if err = randomize.Struct(seed, inputTwo, inputDBTypes, false, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = inputOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = inputTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Inputs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testInputsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	inputOne := &Input{}
	inputTwo := &Input{}
	if err = randomize.Struct(seed, inputOne, inputDBTypes, false, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}
	if err = randomize.Struct(seed, inputTwo, inputDBTypes, false, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = inputOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = inputTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Inputs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testInputsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Inputs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testInputsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(inputColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Inputs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testInputsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testInputsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := InputSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testInputsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Inputs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	inputDBTypes = map[string]string{`ID`: `bigint`, `Name`: `character varying`, `OwnerID`: `bigint`, `Inputtype`: `character varying`, `Description`: `character varying`, `Version`: `bigint`}
	_            = bytes.MinRead
)

func testInputsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(inputPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(inputAllColumns) == len(inputPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Inputs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, inputDBTypes, true, inputPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testInputsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(inputAllColumns) == len(inputPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Input{}
	if err = randomize.Struct(seed, o, inputDBTypes, true, inputColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Inputs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, inputDBTypes, true, inputPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(inputAllColumns, inputPrimaryKeyColumns) {
		fields = inputAllColumns
	} else {
		fields = strmangle.SetComplement(
			inputAllColumns,
			inputPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := InputSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testInputsUpsert(t *testing.T) {
	t.Parallel()

	if len(inputAllColumns) == len(inputPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Input{}
	if err = randomize.Struct(seed, &o, inputDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Input: %s", err)
	}

	count, err := Inputs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, inputDBTypes, false, inputPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Input struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Input: %s", err)
	}

	count, err = Inputs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
