// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package psql_model

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accounts", testAccountsUpsert)

	t.Run("Channels", testChannelsUpsert)

	t.Run("GorpMigrations", testGorpMigrationsUpsert)

	t.Run("Messages", testMessagesUpsert)
}
