// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package rest

const (
	BasicAuthScopes = "basicAuth.Scopes"
)

// ErrorResp defines model for ErrorResp.
type ErrorResp struct {
	HttpStatus int     `json:"http_status"`
	Message    *string `json:"message,omitempty"`
	Name       string  `json:"name"`
}

// RegisterReqBody defines model for RegisterReqBody.
type RegisterReqBody struct {
	TelegramId int64 `json:"telegramId"`
}

// SuccessResp defines model for SuccessResp.
type SuccessResp struct {
	Success bool `json:"success"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody RegisterReqBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody
