version: '3'
services:
  send_to_channels_bot:
    build: .
    env_file:
      - .env
    networks:
      - internal
      - external
networks:
  internal:
    name: internal
    internal: true
  external:
